---
# tasks for developer role
- name: Install developer packages
  become: true
  ansible.builtin.apt:
    name:
      - gcc
      - make
      - python3
      - python3-pip
    state: present

- name: Install golang
  ansible.builtin.apt:
    name:
      - golang
    state: present

- name: Install elixir
  ansible.builtin.apt:
    name:
      - erlang
      - elixir
      - erlang-doc
    state: present

- name: Install flatpack
  ansible.builtin.apt:
    name:
      - flatpak
    state: present

- name: Enable flathub repo
  become: false
  ansible.builtin.command: "flatpak remote-add --if-not-exists --user flathub https://flathub.org/repo/flathub.flatpakrepo"

- name: Install podman
  ansible.builtin.apt:
    name:
      - podman
    state: present

- name: Install podman-desktop
  become: false
  ansible.builtin.command: flatpak install -y flathub io.podman_desktop.PodmanDesktop

- name: Install gitnuro (git GUI)
  become: false
  ansible.builtin.command: flatpak install -y flathub com.jetpackduba.Gitnuro

# VS Code install
- name: Install VS Code on Debian/Ubuntu
  block:
    - name: Check the system architecture
      ansible.builtin.command: uname -m
      register: architecture
    
    - name: Set VS Code download URL based on architecture
      set_fact:
        vscode_url: >
          {% if architecture.stdout == "x86_64" %}
          https://go.microsoft.com/fwlink/?LinkID=760868
          {% elif architecture.stdout == "arm64" %}
          https://update.code.visualstudio.com/latest/linux-deb-arm64/stable
          {% elif architecture.stdout == "aarch64" %}
          https://update.code.visualstudio.com/latest/linux-deb-arm64/stable
          {% elif architecture.stdout == "amd64" %}
          https://go.microsoft.com/fwlink/?LinkID=760868
          {% else %}
          ""
          {% endif %}

    - name: Fail if unsupported architecture
      ansible.builtin.fail:
        msg: "Unsupported architecture: {{ architecture.stdout }}"
      when: vscode_url == ""
    
    - name: Check if VS Code is installed
      shell: dpkg -s code | grep "ok installed"
      register: vscode_installed
      ignore_errors: true
      changed_when: false

- name: Install VS Code on Debian/Ubuntu
  block:

    - name: Add arm64 architecture
      ansible.builtin.command: dpkg --add-architecture arm64
      become: yes
      when: architecture.stdout == "arm64" or architecture.stdout == "aarch64"

    - name: Update apt package list
      ansible.builtin.apt:
        update_cache: yes
      become: yes
      when: architecture.stdout == "arm64" or architecture.stdout == "aarch64"
    
    - name: Debug message of URL being used
      ansible.builtin.debug:
        msg: 
          - "Architecture {{ architecture.stdout }}"
          - "Pulling VS Code from {{ vscode_url }}"

    - name: Download VS Code
      ansible.builtin.get_url:
        url: "{{ vscode_url }}"
        dest: /tmp/vscode.deb
        force: true

    - name: Install VS Code
      ansible.builtin.apt:
        deb: /tmp/vscode.deb
        state: present
  when: vscode_installed.rc != 0 and (ansible_distribution == 'Debian' or ansible_distribution == 'Ubuntu')
  become: true #redundant but good practice
